version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: smart-laundry-mqtt
    ports:
      - "1883:1883"    # MQTT port
      - "9001:9001"    # WebSocket port
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./passwd:/mosquitto/config/passwd
      - ./acl:/mosquitto/config/acl
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
    restart: unless-stopped
    networks:
      - laundry-network

volumes:
  mosquitto-data:
  mosquitto-logs:

networks:
  laundry-network:
    external: true
